**Training a neural network to calculate a product using tensorflow**

First we import numpy and tensorflow

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

ModuleNotFoundError: No module named 'tensorflow'

Create training data randomly generated for demonstration purposes all values in [0,1] with uniform distribution

In [152]:

def create_data(n_observations):
    train_data = np.random.rand(2*n_observations).reshape((n_observations, 2))
    label_data = train_data[:,0] * train_data[:,1]
    return train_data, label_data


In [153]:
X, y = create_data(10000)

print(X)
print(y)


[[0.55875016 0.15422988]
 [0.30767267 0.4094162 ]
 [0.63447021 0.69576954]
 ...
 [0.92094793 0.67119349]
 [0.27834005 0.86707646]
 [0.69575647 0.02853114]]
[0.08617597 0.12596618 0.44144505 ... 0.61813426 0.2413421  0.01985072]


**Creating the model**

Input has a shape of 2 (pair of values)

3 layers of neurons

2 dense layers with 16 neurons each and relu activation function

last dense layer for an output of a single numerical value linear activation

In [154]:
model = keras.Sequential(
    [
        keras.Input(shape=(2,)),
        layers.Dense(16, activation="relu"),
        layers.Dense(16, activation="relu"),
        layers.Dense(1, activation="linear"),
    ]
)

model.summary()

Model: "sequential_37"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_111 (Dense)                    │ (None, 16)                  │              48 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_112 (Dense)                    │ (None, 16)                  │             272 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_113 (Dense)                    │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 337 (1.32 KB)

 Trainable params: 337 (1.32 KB)

 Non-trainable params: 0 (0.00 B)

Compiling the model will set up optimizer, loss, etc.
Training is done in batches. We use 10 epochs of training

In [155]:
model.compile(optimizer='Adam', loss='mean_squared_error')
model.fit(X, y, epochs=10, batch_size=10)




Epoch 1/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0251
Epoch 2/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0023
Epoch 3/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.0016
Epoch 4/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.0012
Epoch 5/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3036e-04
Epoch 6/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 6.6708e-04
Epoch 7/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 5.7230e-04
Epoch 8/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 4.9507e-04
Epoch 9/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 4.4797e-04
Epoch 10/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 4.0022e-04


We create a small test dataset to test the output of our model. Compare results with test_y target values

In [156]:
test_data, test_y = create_data(10)
results = model.predict(test_data)

print(test_data)
print(results)
print(test_y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
[[0.89253396 0.90142605]
 [0.17001353 0.1253824 ]
 [0.23378214 0.31049096]
 [0.28992101 0.26122983]
 [0.07386761 0.67976381]
 [0.06263586 0.89569001]
 [0.57722189 0.32109076]
 [0.6036139  0.45853997]
 [0.69509661 0.18193086]
 [0.58767732 0.02230233]]
[[0.78316456]
 [0.02585541]
 [0.05486099]
 [0.0580324 ]
 [0.05578402]
 [0.0822968 ]
 [0.18506482]
 [0.30281118]
 [0.13033086]
 [0.00408627]]
[0.80455336 0.0213167  0.07258724 0.07573602 0.05021253 0.05610231
 0.18534061 0.2767811  0.12645952 0.01310657]
